### ISSUE TITLE
NestedScrollView   and  SwipeRefreshLayout

### ISSUE THREAD

**Issue by jayronlou** [mugku/CoordinatorLayoutHelper#3]
If  i want to achieve  NestedScrollView and swipeRefreshLayout  effect，How  can I do

**Comment by mugku** [comment]
Hi~ jayronlou

I don't understand What do you want.. 
Give me more explanation

and I think you should see https://developer.android.com/intl/ko/reference/android/support/v4/widget/SwipeRefreshLayout.html.

Best Regards
