### ISSUE TITLE
Can I use ListView?

### ISSUE THREAD

**Issue by gnehsuy** [mugku/CoordinatorLayoutHelper#4]
Hi,I use ListView instead of RecyclerView，and I can not get the effect，what can I do?（My English is not good,sorry，I am chinese）

**Comment by mugku** [comment]
Hi~ gnehsuy  ~ 

Sorry.. I'm so late..
I will check it....

Best Regards

**Comment by mugku** [comment]
Hi ~

I'm so late... so so sorry.. 
I think to use listview is not good.

i recommend to use recyclerview

thanks
